version: '3.8'

services:
  app:
    build: .
    container_name: ab-testing-api
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - AWS_REGION=us-east-1
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - EXPERIMENTS_TABLE=ab-testing-experiments
      - ASSIGNMENTS_TABLE=ab-testing-assignments
      - EVENTS_TABLE=ab-testing-events
    volumes:
      - ./:/app
    depends_on:
      - redis
      - dynamodb-local
    networks:
      - ab-testing-network

  redis:
    image: redis:alpine
    container_name: ab-testing-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - ab-testing-network
    volumes:
      - redis-data:/data

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: ab-testing-dynamodb
    restart: always
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"
    volumes:
      - dynamodb-data:/home/dynamodblocal/data
    networks:
      - ab-testing-network

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    container_name: ab-testing-dynamodb-admin
    restart: always
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
    depends_on:
      - dynamodb-local
    networks:
      - ab-testing-network

volumes:
  redis-data:
  dynamodb-data:

networks:
  ab-testing-network:
    driver: bridge